[package]
name = "chance-encounters"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2.92"
js-sys = "0.3"
console_error_panic_hook = "0.1.7"
chrono = { version = "0.4.38", features = ["serde"] }
rstar = "0.12.0"
shrinkwraprs = "0.3.0"
quick-xml = { version = "0.35.0", features = ["serialize"] }
